server {
    listen 80;
    server_name _;

    client_max_body_size 20M;

    root /var/www/project-fyp-mall;
    index index.html;

    location = /fyp {
        return 301 /fyp/;
    }

    location ^~ /fyp/ {
        alias /var/www/project-fyp-mall-fyp/;
        index index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:9191/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}
